version: '3.4'

services:
  mongodb:
    container_name: mongo-db
    image: mongo
    ports:
      - 9001:27017

  tick-tack-toe:
    image: ${DOCKER_REGISTRY-}ticktacktoe
    build:
      context: .
      dockerfile: tick-tack-toe/Dockerfile
    ports:
      - 9002:80 
    environment:
      - DB_HOST=mongodb
      - DB_NAME=game